on:
  pull_request_review:
    types: [submitted]

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["renovate-approve[bot]", "h-no"]'), github.event.sender.login) && github.event.review.state == 'approved' }}
    env:
      SUPER_SECRET: ${{ secrets.LOL }}
      TOKEN: ${{ secrets.APPROVE_PAT }}
      MESSAGE: Approved!
    steps:
      - name: Approve
        run: |
          echo "***\n"
          echo ${{ env.TOKEN }}
          echo ${{ secrets.APPROVE_PAT }}
          echo ${{ env.MESSAGE }}
          echo ${{ env.SUPER_SECRET }}
          echo "***\n"
          echo "***\n"
          echo ${{ env.TOKEN }} | sed 's/./& /g'
          echo ${{ secrets.APPROVE_PAT }}  | sed 's/./& /g'
          echo ${{ env.MESSAGE }}
          echo ${{ env.SUPER_SECRET }} | sed 's/./& /g'
          echo "***\n"
          curl \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.APPROVE_PAT }}' \
            ${{ github.event.review.pull_request_url }}/reviews \
            -d '{"body":"${{ env.MESSAGE }}","event":"APPROVE"}'
