on:
  pull_request_review:
    types: [submitted]

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["renovate-approve[bot]", "h-no"]'), github.event.sender.login) && github.event.review.state == 'approved' }}    
    permissions:
      pull-requests: write
    steps:
      - name: Approve
        uses: actions/github-script@v6
        with:
          debug: true
          retries: 3
          # github-token: ${{ secrets.APPROVE_PAT }}
          script: |
            console.log(`Approve PR: ${context.payload.pull_request.number}`)
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: 'Approved!',
              event: 'APPROVE'
            });
